baseURL = "http://example.org/"
languageCode = "en-us"
title = "Fundaci칩n Viva Juntos por la Ni침ez de El Salvador"
theme = "airspace-hugo"


[menu]
    [[menu.header]]
        weight = 1
        name = "Our Mission"
        url = "/our-mission"
    [[menu.header]]
        weight = 2
        name = "Blog"
        url = "/blog"

[params]
    home="Home"

    [params.slider]
        enable=true
        title="Fundaci칩n Viva Juntos por la Ni침ez de El Salvador"

    [params.wrapper]
        enable=true
        title="About Us"
