baseURL = "https://childrens-foundation-el-salvador.github.io/website"
DefaultContentLanguage = "es"
title = "Fundación Viva Juntos por la Niñez de El Salvador"

[params]
    dateFormat = "6 January 2006"

[languages]
    [languages.es]
        home = "Home"
        contentDir = "content/es"

        [languages.es.slider]
        enable = true
        title = "Fundación Viva Juntos por la Niñez de El Salvador"

        [languages.es.wrapper]
        enable = true
        title = "Quienes somos"
        paragraph = """
            Organización Cristiana humanitaria comprometida con la prevención, protección y restitución de derechos de
            niñez adolescencia y sus familias domiciliadas en zonas de alto riesgo social , familiar y ambiental.
            """

        [languages.es.feature]
        enable = true
        title = "Que hacemos"
        paragraph = """
            Acompañamos a 21 Iglesias, Centros Escolares, Comunidades, Centros de acogimiento  y Fundaciones. 2,700 niñas,
            niños y adolescentes domiciliados en zonas de alto riesgo familiar, social y ambiental. Acompañados a través
            de procesos educativos, preventivos  y de sensibilización.
            """

        [languages.es.blog]
        enable = true
        title = "Get The Latest On What We're doing"
        subtitle = "Catch up with us, anytime and anywhere"

        [languages.es.call]
            enable = true
            title = "Haz una donación"

        [languages.es.contact]
            enable = true
            title = "Drop us a note"
            subtitle = "Don’t just take our word for it. Check out some of our latest work."
        [languages.es.contact.form]
            name = "Your name"
            email = "Your email"
            subject = "Your subject"
            message = "Your message"
            button = "Send message"
        [languages.es.contact.box]
            title = "Stop by for a visit"
            address = "North Main Street, Brooklyn Australia"
            email = "Email: contact@mail.com"
            phone = "Phone: +88 01672 506 744"
        [languages.es.contact.gmaps]
            title = "We Also Count in Google Maps"

        [languages.es.menu]
            [[languages.es.menu.header]]
                weight = 2
                name = "Nuestros socios"
                url = "nuestros-socios"
            [[languages.es.menu.header]]
                weight = 3
                name = "Visión"
                url = "vision"
            [[languages.es.menu.header]]
                weight = 4
                name = "Misión"
                url = "mision"
            [[languages.es.menu.header]]
                weight = 5
                name = "Valores"
                url = "valores"
            [[languages.es.menu.header]]
                weight = 6
                name = "Contáctanos"
                url = "contactanos"

            [[languages.es.menu.footer]]
                weight = 1
                name = "Nuestros socios"
                url = "nuestros-socios"
            [[languages.es.menu.footer]]
                weight = 2
                name = "Visión"
                url = "vision"
            [[languages.es.menu.footer]]
                weight = 3
                name = "Misión"
                url = "Misión"
            [[languages.es.menu.footer]]
                weight = 5
                name = "Valores"
                url = "valores"
            [[languages.es.menu.footer]]
                weight = 6
                name = "Contáctanos"
                url = "contactanos"
            [[languages.es.menu.footer]]
                weight = 7
                name = "Facebook"
                url = "https://www.facebook.com/Fundaci%C3%B3n-Viva-Juntos-por-la-Ni%C3%B1ez-de-El-Salvador-545856865515974"

    [languages.en]
        home = "Home"
        contentDir = "content/en"

        [languages.en.slider]
        enable = true
        title = "Fundación Viva Juntos por la Niñez de El Salvador"

        [languages.en.wrapper]
        enable = true
        title = "Visión"
        paragraph = """
            Ser una Fundación Cristiana, comprometida con la protección y restitución de derechos de niñas, niños y
            adolescentes Salvadoreños por medio de un enfoque de derechos humanos de la niñez en armonía con la palabra
            de Dios."""

        [languages.en.blog]
        enable = true
        title = "Get The Latest On What We're doing"
        subtitle = "Catch up with us, anytime and anywhere"

        [languages.en.feature]
        enable = true
        title = "Misión"
        paragraph = """
            Promover acciones preventivas, de acompañamiento y restitución de derechos a niñez y adolescencia, a través
            de alianzas estratégicas, con el fin de procurar su desarrollo integral desde la familia, Estado y sociedad
            en el marco de sus derechos y responsabilidades."""

        [languages.en.call]
            enable = true
            title = "We design delightful digital experiences."
            paragraph = """
                Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve
                achieved for other clients, and meet our highly experienced Team who just love to design."""

        [languages.en.contact]
            enable = true
            title = "Drop us a note"
            subtitle = "Don’t just take our word for it. Check out some of our latest work."
        [languages.en.contact.form]
            name = "Your name"
            email = "Your email"
            subject = "Your subject"
            message = "Your message"
            button = "Send message"
        [languages.en.contact.box]
            title = "Stop by for a visit"
            address = "North Main Street, Brooklyn Australia"
            email = "Email: contact@mail.com"
            phone = "Phone: +88 01672 506 744"
        [languages.en.contact.gmaps]
            title = "We Also Count in Google Maps"

        [languages.en.menu]
            [[languages.en.menu.header]]
                weight = 2
                name = "Our Partners"
                url = "our-partners"
            [[languages.en.menu.header]]
                weight = 3
                name = "Vision"
                url = "vision"
            [[languages.en.menu.header]]
                weight = 4
                name = "Mission"
                url = "mission"
            [[languages.en.menu.header]]
                weight = 5
                name = "Values"
                url = "values"
            [[languages.en.menu.header]]
                weight = 6
                name = "Contact"
                url = "contact"

            [[languages.en.menu.footer]]
                weight = 1
                name = "Our Partners"
                url = "our-partners"
            [[languages.en.menu.footer]]
                weight = 2
                name = "Vision"
                url = "vision"
            [[languages.en.menu.footer]]
                weight = 3
                name = "Mission"
                url = "mission"
            [[languages.en.menu.footer]]
                weight = 5
                name = "Values"
                url = "values"
            [[languages.en.menu.footer]]
                weight = 6
                name = "Contact"
                url = "contact"
            [[languages.en.menu.footer]]
                weight = 7
                name = "Facebook"
                url = "https://www.facebook.com/Fundaci%C3%B3n-Viva-Juntos-por-la-Ni%C3%B1ez-de-El-Salvador-545856865515974"
