title = "Fundación Viva Juntos por la Niñez de El Salvador"
languageCode = "en-us"

[menu]
    [[menu.header]]
        weight = 2
        name = "Our Mission"
        url = "/our-mission"
    [[menu.header]]
        weight = 3
        name = "Blog"
        url = "/blog"
    [[menu.header]]
        weight = 4
        name = "Contact"
        url = "/contact"
    [[menu.header]]
        weight = 5
        name = "Facebook"
        url = "https://www.facebook.com/Fundaci%C3%B3n-Viva-Juntos-por-la-Ni%C3%B1ez-de-El-Salvador-545856865515974/"

    [[menu.footer]]
        weight = 1
        name = "Our Mission"
        url = "/our-mission"
    [[menu.footer]]
        weight = 2
        name = "Blog"
        url = "/blog"
    [[menu.footer]]
        weight = 3
        name = "Contact"
        url = "/contact"

    [[menu.footer]]
        weight = 4
        name = "Facebook"
        url = "https://www.facebook.com/Fundaci%C3%B3n-Viva-Juntos-por-la-Ni%C3%B1ez-de-El-Salvador-545856865515974/"

# The site's parameters
[params]
    home = "Home"
    dateFormat = "6 January 2006"

    [params.slider]
    enable = true
    title = "Fundación Viva Juntos por la Niñez de El Salvador"

    [params.wrapper]
    enable = true
    title = "Visión"
    paragraph = "Ser una Fundación Cristiana, comprometida con la protección y restitución de derechos de niñas, niños y adolescentes Salvadoreños por medio de un enfoque de derechos humanos de la niñez en armonía con la palabra de Dios."

    [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

    [params.feature]
    enable = true
    title = "Misión"
    content = "Promover acciones preventivas, de acompañamiento y restitución de derechos a niñez y adolescencia, a través de alianzas estratégicas, con el fin de procurar su desarrollo integral desde la familia, Estado y sociedad en el marco de sus derechos y responsabilidades."

    [params.call]
    enable = true
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

    [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
    name = "Your name"
    email = "Your email"
    subject = "Your subject"
    message = "Your message"
    button = "Send message"
    [params.contact.box]
    title = "Stop by for a visit"
    address = "North Main Street, Brooklyn Australia"
    email = "Email: contact@mail.com"
    phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
    title = "We Also Count in Google Maps"
